### ISSUE TITLE
newly introduced workflow fails

### ISSUE THREAD

**Issue by teobais** [utrechtjug/devoxx4kids#13]
after merging #12 , the newly introduced workflow fails. Been time poor these days, could you please look into it @mdpadberg @mthoolen ? Thanks

**Comment by mdpadberg** [comment]
@teobais 
I cannot access the settings of this project. 
But can you try go to: settings -> Pages -> Source -> put it on Github Actions 
Like [this](https://i.stack.imgur.com/5o6Zj.png) 

Source:
https://stackoverflow.com/questions/73937666/configure-github-pages-failed

**Comment by mdpadberg** [comment]
@teobais I see that the github action is now green and working. So I assume that the suggested fix worked and will close this issue :)
